/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mib;

import javax.swing.JOptionPane;

/**
 *
 * @author joakimfockstedt
 */
public class BytaLösenord extends javax.swing.JFrame {

    private Validering validering;
    private Databas db;
    private String nyttLösenord;
    private String anvID;
    private String anvTyp;
    /**
     * Creates new form BytaLösenord
     */
    public BytaLösenord(String anvID, String anvTyp) {
        initComponents();
        validering = new Validering();
        db = new Databas();
        this.anvID = anvID;
        this.anvTyp = anvTyp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtEpost = new javax.swing.JTextField();
        pwNuvarandeLösenord = new javax.swing.JPasswordField();
        pwNyttLösenord = new javax.swing.JPasswordField();
        lblBytLösenord = new javax.swing.JLabel();
        lblEpost = new javax.swing.JLabel();
        lblNuvarandeLösenord = new javax.swing.JLabel();
        lblNyttLösenord = new javax.swing.JLabel();
        btnBytLösenord = new javax.swing.JButton();
        btnTillbaka = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtEpost.setColumns(20);

        pwNuvarandeLösenord.setColumns(25);

        pwNyttLösenord.setColumns(20);

        lblBytLösenord.setText("Byt Lösenord");

        lblEpost.setText("Epost");

        lblNuvarandeLösenord.setText("Nuvarande Lösenord");

        lblNyttLösenord.setText("Nytt Lösenord");

        btnBytLösenord.setText("Byt lösenord");
        btnBytLösenord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBytLösenordActionPerformed(evt);
            }
        });

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(125, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblNyttLösenord)
                            .addComponent(lblNuvarandeLösenord)
                            .addComponent(lblEpost)
                            .addComponent(pwNyttLösenord)
                            .addComponent(txtEpost)
                            .addComponent(pwNuvarandeLösenord, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(120, 120, 120))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnBytLösenord)
                        .addGap(198, 198, 198))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(lblBytLösenord))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnTillbaka)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblBytLösenord)
                .addGap(61, 61, 61)
                .addComponent(lblEpost)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(lblNuvarandeLösenord)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pwNuvarandeLösenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNyttLösenord)
                .addGap(3, 3, 3)
                .addComponent(pwNyttLösenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBytLösenord)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTillbaka)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBytLösenordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBytLösenordActionPerformed
        String epost = txtEpost.getText();
        valideraNyalösenordet();
        String nuvarandeLösenord = pwNuvarandeLösenord.getText(); 
        //Agent lösenord
        if(validering.getÄrEpostAgent(epost)){
            if(validering.valideraAgentLösenord(nuvarandeLösenord, epost)){
                    db.setAgentLösenordFrånEpost(epost, nyttLösenord);
                    JOptionPane.showMessageDialog(null, "Bytte lösenord.");
            }
            else{
                JOptionPane.showMessageDialog(null, "Felskrivet lösenord.");
            }
        }
        //Alien lösenord
        else{
            if(validering.valideraAlienEpostExisterar(epost, false)){
                db.setAlienLösenordFrånEpost(epost, nyttLösenord);
                JOptionPane.showMessageDialog(null, "Bytte lösenord.");
            }
            else{
                JOptionPane.showMessageDialog(null, "Felskrivet lösenord.");
            }
        }
    }//GEN-LAST:event_btnBytLösenordActionPerformed

    //Tillbaka till hemsidan
    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        if(anvTyp.equals("Agent")){
            AgentHemsida agentHemsida = new AgentHemsida(anvID, anvTyp);
            agentHemsida.show();
            dispose();
        }
        else if(anvTyp.equals("Admin")){
            AdminHemsida adminsida = new AdminHemsida(anvID, anvTyp);
            adminsida.show();
            dispose();
        }
    }//GEN-LAST:event_btnTillbakaActionPerformed
   
    private void valideraNyalösenordet(){
        if(validering.valideraLösenord(pwNyttLösenord.getText())){
            nyttLösenord = pwNyttLösenord.getText();
        }
        else{
            JOptionPane.showMessageDialog(null, "Nya lösenordet är felskrivet.");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBytLösenord;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JLabel lblBytLösenord;
    private javax.swing.JLabel lblEpost;
    private javax.swing.JLabel lblNuvarandeLösenord;
    private javax.swing.JLabel lblNyttLösenord;
    private javax.swing.JPasswordField pwNuvarandeLösenord;
    private javax.swing.JPasswordField pwNyttLösenord;
    private javax.swing.JTextField txtEpost;
    // End of variables declaration//GEN-END:variables
}
